### ISSUE TITLE
Add an option for weather condition's text on plasma/latte-dock panel

### ISSUE THREAD

**Issue by alazkaaa** [rliwoch/plasmoid-wunderground-extended#2]
Is it possible to add weather condition's text on plasma/latte-dock panel (similar to gnome's openweather or even windows :P)?

Thank you 
![askubuntu](https://user-images.githubusercontent.com/89382291/163525241-d0fb2cd0-4bff-43a1-b960-d20edd818c8e.png)
![fedoramagazine](https://user-images.githubusercontent.com/89382291/163525244-6a15c005-be54-4704-beb1-fb902c3f14a2.png)

**Comment by rliwoch** [comment]
Sure, no problem. I'll add a config option for that

**Comment by rliwoch** [comment]
Is that what you're after? 
![image](https://user-images.githubusercontent.com/26857299/163680475-c88e11b9-d2e3-4b28-9d8b-f57911cd617e.png)

Would you be willing to help me test it? Working with Plasma's taskbar scaling is always a bit of a pain. I usually test that on 3 different machines with different DPIs but still, that's a very small subset of possible sizes and shapes of taskbars.

Also, I'm only making it available in horizontal view, as it's pointless to have a longer text in vertical taskbars

**Comment by rliwoch** [comment]
added in v0.5.0

**Comment by alazkaaa** [comment]
Thank you, it works great. Currently I'm on laptop with font DPI forced to 66 and the smallest size of the latte-dock's panel.

![Screenshot_20220418_101453](https://user-images.githubusercontent.com/89382291/163748966-b0ee3836-b359-4a1b-9d1e-9b5df8dec762.png)

**Comment by rliwoch** [comment]
Thanks @alazkaaa
Good to hear (and see) that.
