### ISSUE TITLE
Widget won't refresh automatically

### ISSUE THREAD

**Issue by draeklae** [rliwoch/plasmoid-wunderground-extended#20]
**Describe the bug**
Widget won't refresh automatically (e.g., update current temperature). Refresh only works by manually clicking the "Refresh all data" button.

**To Reproduce**
Noticed the problem ever since installing widget.

**Desktop (output of `plasmashell --version && kf5-config --version`):**
plasmashell 5.24.4
Qt: 5.15.3
KDE Frameworks: 5.93.0
kf5-config: 1.0

**Additional context**
Using Arch Linux (latest).

**Comment by rliwoch** [comment]
Hi @draeklae,

Can you please elaborate a bit more, I'm surprised to see that dosn't work, as the auto refresh is a fundamental functionality based on the Timer running inside the plasmoid.
Are you using Station ID or you're in the "I'm travelling mode" in the plugin?
Did any errors appear in the widget itself?

**Comment by solofolos** [comment]
I can confirm that the plasmoid doesn't update automatically, neither in travelling mode or in station id.
Changing the refresh options does nothing, only updated manually

plasmashell 5.24.4
Qt: 5.15.3
KDE Frameworks: 5.93.0
kf5-config: 1.0

KDE Neon

**Comment by rliwoch** [comment]
ok, thanks, that's some nasty regression in 0.7.0, I think I managed to reproduce it.
I'm working on changing the refresh mechanism and getting rid of stations IDs for those who don't need/want wunderground - just weather for their location.
Before that, I'll take at the current mainline and issue some emergency fix

**Comment by rliwoch** [comment]
@solofolos @draeklae 
I've just published v0.7.1 in the marketplace, it should be available for automatic download in 30-60 minutes, maybe earlier.
I'd really appreciate if you could test it and let me know

**Comment by solofolos** [comment]
The plasmoid automatically refreshes again in both modes. Thanks for your work.

**Comment by rliwoch** [comment]
Closing the issue as resolved
