### ISSUE TITLE
Can't find "I'm traveling" mode

### ISSUE THREAD

**Issue by embeddedt** [rliwoch/plasmoid-wunderground-extended#33]
There is an "I'm traveling" mode documented that will automatically find an appropriate weather station based on my location, but I don't see the GUI option to enable it. I have looked on the weather details panel and in Settings. I'm sure I'm just blind, can I have a screenshot please?

**Comment by Leonerd-04** [comment]
![image](https://user-images.githubusercontent.com/87563929/191892957-e182384b-d194-4519-95a2-9522b6efbfcf.png)
![image](https://user-images.githubusercontent.com/87563929/191892902-0b18d530-f928-4142-989a-c18a857b74c3.png)

I have the same issue; it seems like the icon doesn't render. You can see that my mouse hovers over the position where the airplane icon is in the first image, and there's a button there, just no icon. I tried changing my icon set, no luck. I tried disabling kvantum, also no luck.

The mode is still usable, just really hard to find.

**Comment by embeddedt** [comment]
Forgot to close this, thank you for the reply. This worked well.
